# Generated by Django 4.2.7 on 2024-05-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ab_img',
            options={'ordering': ('alt',), 'verbose_name_plural': 'About images'},
        ),
        migrations.AlterModelOptions(
            name='ab_list',
            options={'ordering': ('title',), 'verbose_name_plural': 'About feats'},
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('about_title',), 'verbose_name_plural': 'About Content'},
        ),
    ]
