# Generated by Django 4.2.7 on 2024-05-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ab_img_options_alter_ab_list_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='button_title',
            field=models.CharField(default='Explore Now', max_length=255),
        ),
    ]
