# Generated by Django 4.2.7 on 2024-05-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hero_button_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ab_list',
            options={'ordering': ('title',), 'verbose_name_plural': 'About list'},
        ),
    ]
