# Generated by Django 4.2.7 on 2024-05-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ab_list_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='about',
            name='ab_img',
        ),
        migrations.RemoveField(
            model_name='about',
            name='ab_list',
        ),
        migrations.AddField(
            model_name='about',
            name='ab_img',
            field=models.ManyToManyField(blank=True, to='core.ab_img'),
        ),
        migrations.AddField(
            model_name='about',
            name='ab_list',
            field=models.ManyToManyField(blank=True, to='core.ab_list'),
        ),
    ]
