# Generated by Django 4.2.7 on 2024-05-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_about_about_content_remove_about_ab_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('ans', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'FAQ',
                'ordering': ('question',),
            },
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pageFiles/images')),
            ],
            options={
                'verbose_name_plural': 'Showcase Images',
                'ordering': ('alt',),
            },
        ),
    ]
