# Generated by Django 4.2.7 on 2024-06-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hero_bg_img_alter_hero_bg_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_title', models.CharField(max_length=255)),
                ('cta_content', models.TextField(blank=True, null=True)),
                ('cta_btn_url', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_btn_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'CTA',
                'ordering': ('cta_title',),
            },
        ),
    ]
