# Generated by Django 4.2.7 on 2024-06-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('highlight', models.CharField(max_length=2500)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pageFiles/blogimages')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog posts',
                'ordering': ('title',),
            },
        ),
    ]
